version: '3.8'

services:
  postgres:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: