# Generated by Django 4.0.4 on 2022-06-29 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'فرمت شماره وارد شده صحیح نیست (شماره باید با ۰۹ شروع شود)')]),
        ),
    ]
