# Generated by Django 4.0.4 on 2022-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cost",
            field=models.PositiveIntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="time_period",
            field=models.CharField(default="1", max_length=60),
            preserve_default=False,
        ),
    ]
