# Generated by Django 4.0.4 on 2022-05-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_contractor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.contractor",
            ),
        ),
    ]
