# Generated by Django 4.0.4 on 2022-06-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_period',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
