# Generated by Django 4.0.4 on 2022-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_time_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[("P", "Pending"), ("W", "Waiting"), ("D", "Done")],
                default="P",
                max_length=1,
            ),
        ),
    ]
